//! `meta.toml` sidecars — the human/agent-resolved companion to a
//! [`crate::propose::Proposal`] (`SOPACK-1.0-PLAN.md` §3.5).
//!
//! The loop the plan describes: `propose` drafts candidates -> an
//! agent/human resolves each field (researching where needed: the year
//! trap, an author name form, archive provenance) -> [`write_template`]
//! writes `<source>.meta.toml` pre-filled with what `propose` already
//! resolved and the remaining candidates as commented-out choices ->
//! [`load`] reads it back -> [`ExtractOptions::from_meta`] turns it into
//! options `extract` accepts -> [`check_complete`] refuses (exit 4, via
//! [`crate::ErrorCode::NeedsMetadata`]) if a field `extract` cannot derive
//! from the source itself is still missing, *before* the (possibly slow)
//! extraction runs.
//!
//! `check_complete` is a **preflight convenience**, not a replacement for
//! [`sopack_book::validate`]: some fields (an EPUB's OPF title, a
//! `sop_json` file's own meta block) may still resolve once the source is
//! actually read, even though the merged options alone don't show it yet.
//! A caller should still run `sopack_book::validate` on the extracted
//! [`sopack_book::Book`] as the final, authoritative check — this module
//! only lets `extract --meta` fail fast on what it can already tell from
//! the sidecar plus explicit flags, for the fields no extractor in this
//! crate ever derives from the source (see the per-kind tables in
//! [`required_fields`]'s doc comment).

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::error::{ErrorCode, ExtractError};
use crate::options::{ExtractOptions, Kind};
use crate::propose::Proposal;

/// `<source>.meta.toml`'s shape: the same field names as
/// [`ExtractOptions`], plus an optional `[evidence]` table (free text per
/// field, e.g. `title = "title page p.1; year from imprint"`) a human or
/// agent leaves for the next reviewer.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MetaFile {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub book_code: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub year: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub corpus: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub book_pair: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub acquired_from: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rights: Option<String>,
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub evidence: HashMap<String, String>,
}

/// Parse *path* as a `meta.toml` sidecar.
pub fn load(path: &Path) -> Result<MetaFile, ExtractError> {
    let text = std::fs::read_to_string(path)
        .map_err(|e| ExtractError::input_invalid(format!("cannot read {}: {e}", path.display())))?;
    toml::from_str(&text).map_err(|e| {
        ExtractError::input_invalid(format!("{}: not a valid meta.toml: {e}", path.display()))
    })
}

fn toml_string(s: &str) -> String {
    toml::Value::String(s.to_string()).to_string()
}

/// Write `<source>.meta.toml` next to (or at) *out_path*, pre-filled from
/// *proposal*: every field `propose` already resolved is written live,
/// every unresolved field is left commented out with its candidates listed
/// (value, source, evidence/warning) so a reviewer copies the right line in
/// rather than retyping it.
pub fn write_template(proposal: &Proposal, out_path: &Path) -> Result<(), ExtractError> {
    let text = render_template(proposal);
    if let Some(parent) = out_path.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent).map_err(|e| {
                ExtractError::input_invalid(format!("cannot create {}: {e}", parent.display()))
            })?;
        }
    }
    std::fs::write(out_path, text).map_err(|e| {
        ExtractError::input_invalid(format!("cannot write {}: {e}", out_path.display()))
    })
}

fn render_template(proposal: &Proposal) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# meta.toml for {}\n# Generated by `sopack propose` from {} candidate(s) — resolved fields\n\
         # are set below; unresolved fields are commented out with their\n\
         # candidates listed. Pick one, write your own, or leave commented to\n\
         # let `extract --meta` refuse (exit 4) until a human decides.\n\n",
        proposal.source.path,
        proposal.fields.iter().map(|(_, f)| f.candidates.len()).sum::<usize>(),
    ));
    for (name, field) in proposal.fields.iter() {
        if name == "book_pair" {
            // book_pair mirrors book_code by default in every extractor;
            // leaving it out of the template keeps it that way unless the
            // reviewer deliberately adds an override.
            continue;
        }
        match field_value_line(name, field) {
            Some(line) => out.push_str(&format!("{line}\n")),
            None => {
                if field.candidates.is_empty() {
                    out.push_str(&format!("# {name}: no candidates found\n# {name} = \n"));
                } else {
                    out.push_str(&format!(
                        "# {name}: unresolved — {} candidate(s)\n",
                        field.candidates.len()
                    ));
                    for c in &field.candidates {
                        let mut note =
                            format!("#   {} (from: {}", value_to_toml_literal(&c.value), c.from);
                        if let Some(w) = &c.warning {
                            note.push_str(&format!(", warning: {w}"));
                        }
                        if let Some(col) = c.collision {
                            note.push_str(&format!(", collision: {col}"));
                        }
                        note.push(')');
                        out.push_str(&note);
                        out.push('\n');
                        if let Some(ev) = &c.evidence {
                            out.push_str(&format!("#     evidence: {ev}\n"));
                        }
                    }
                    if let Some(first) = field.candidates.first() {
                        out.push_str(&format!(
                            "# {name} = {}\n",
                            value_to_toml_literal(&first.value)
                        ));
                    }
                }
            }
        }
        out.push('\n');
    }
    if !proposal.warnings.is_empty() {
        out.push_str("# propose warnings:\n");
        for w in &proposal.warnings {
            out.push_str(&format!("#   {w}\n"));
        }
    }
    out
}

fn value_to_toml_literal(v: &serde_json::Value) -> String {
    match v {
        serde_json::Value::String(s) => toml_string(s),
        serde_json::Value::Number(n) => n.to_string(),
        other => toml_string(&other.to_string()),
    }
}

fn field_value_line(name: &str, field: &crate::propose::FieldProposal) -> Option<String> {
    match &field.value {
        serde_json::Value::Null => None,
        v => Some(format!("{name} = {}", value_to_toml_literal(v))),
    }
}

impl ExtractOptions {
    /// *meta*'s fields as [`ExtractOptions`] (chunk_limits stays default —
    /// a sidecar never carries chunker tuning). String fields pass through
    /// verbatim; `year` too, since [`MetaFile::year`] is already typed.
    pub fn from_meta(meta: &MetaFile) -> ExtractOptions {
        ExtractOptions {
            book_code: meta.book_code.clone(),
            lang: meta.lang.clone(),
            title: meta.title.clone(),
            author: meta.author.clone(),
            year: meta.year,
            corpus: meta.corpus.clone(),
            slug: meta.slug.clone(),
            book_pair: meta.book_pair.clone(),
            acquired_from: meta.acquired_from.clone(),
            rights: meta.rights.clone(),
            chunk_limits: Default::default(),
        }
    }
}

/// Merge *explicit* (e.g. CLI flags) with *sidecar* (`meta.toml`, via
/// [`ExtractOptions::from_meta`]): a field set in both must agree — a
/// silent pick between two different values is exactly the kind of
/// invention rule #9 forbids — otherwise *explicit* wins when set, else
/// *sidecar* wins, else the field stays `None`. `chunk_limits` always comes
/// from *explicit* (a sidecar never carries it).
pub fn merge(
    explicit: &ExtractOptions,
    sidecar: &ExtractOptions,
) -> Result<ExtractOptions, ExtractError> {
    macro_rules! merge_field {
        ($field:ident, $label:literal) => {{
            match (&explicit.$field, &sidecar.$field) {
                (Some(e), Some(s)) if e != s => {
                    return Err(ExtractError::new(
                        ErrorCode::Usage,
                        format!(
                            "{} conflicts between an explicit option ({:?}) and the meta.toml sidecar ({:?})",
                            $label, e, s
                        ),
                    )
                    .with_field($label))
                }
                (Some(e), _) => Some(e.clone()),
                (None, Some(s)) => Some(s.clone()),
                (None, None) => None,
            }
        }};
    }
    Ok(ExtractOptions {
        book_code: merge_field!(book_code, "book_code"),
        lang: merge_field!(lang, "lang"),
        title: merge_field!(title, "title"),
        author: merge_field!(author, "author"),
        year: merge_field!(year, "year"),
        corpus: merge_field!(corpus, "corpus"),
        slug: merge_field!(slug, "slug"),
        book_pair: merge_field!(book_pair, "book_pair"),
        acquired_from: merge_field!(acquired_from, "acquired_from"),
        rights: merge_field!(rights, "rights"),
        chunk_limits: explicit.chunk_limits,
    })
}

/// The fields *this crate's extractors never derive from the source* for
/// *kind*, i.e. the ones `extract --meta` cannot possibly satisfy unless
/// they arrive via options/sidecar:
///
/// - `markdown`/`text`: `book_code`, `lang`, `title` — both extractors
///   build `book.*` straight from `ExtractOptions`, with **no** fallback
///   to file content (`markdown.rs`/`text.rs`'s `build_book_meta` calls
///   pass `opts.*` through verbatim; see their module doc comments).
/// - `epub`: `book_code` — the inline-citation-code heuristic
///   (`epub::extract`) only fires on a minority of books (Jones/Waggoner's
///   printed-reference convention); title/author/year/rights are left out
///   here because OPF metadata often does supply them (this is exactly why
///   `propose` exists to check).
/// - `sop_json`: nothing — `book_code`/`title`/`year`/`lang` all have a
///   documented fallback onto the file's own structure (`sop_json.rs`).
///
/// `author`/`year` are added on top of this base, for every kind, whenever
/// [`check_complete`]'s options carry a `corpus` — mirroring
/// `sopack_book::validate`'s EGW exemption, and known ahead of extraction
/// because `corpus` is *always* options-only (no extractor infers it).
pub fn required_fields(kind: Kind) -> &'static [&'static str] {
    match kind {
        Kind::Markdown | Kind::Text => &["book_code", "lang", "title"],
        Kind::Epub => &["book_code"],
        Kind::SopJson => &[],
    }
}

/// Preflight completeness check for `extract --meta` — see this module's
/// doc comment and [`required_fields`] for exactly what this does and does
/// not guarantee.
pub fn check_complete(kind: Kind, opts: &ExtractOptions) -> Vec<ExtractError> {
    let mut missing: Vec<&'static str> = required_fields(kind)
        .iter()
        .filter(|f| !opts_has(opts, f))
        .copied()
        .collect();
    if opts.corpus.is_some() {
        for f in ["author", "year"] {
            if !opts_has(opts, f) && !missing.contains(&f) {
                missing.push(f);
            }
        }
    }
    missing
        .into_iter()
        .map(|f| {
            ExtractError::new(
                ErrorCode::NeedsMetadata,
                format!("{f} is required but not given (explicit option or meta.toml sidecar)"),
            )
            .with_field(f)
            .with_hint("write it into the meta.toml sidecar, or pass it explicitly")
        })
        .collect()
}

fn opts_has(opts: &ExtractOptions, field: &str) -> bool {
    match field {
        "book_code" => opts.book_code.is_some(),
        "lang" => opts.lang.is_some(),
        "title" => opts.title.is_some(),
        "author" => opts.author.is_some(),
        "year" => opts.year.is_some(),
        "corpus" => opts.corpus.is_some(),
        "slug" => opts.slug.is_some(),
        "book_pair" => opts.book_pair.is_some(),
        "acquired_from" => opts.acquired_from.is_some(),
        "rights" => opts.rights.is_some(),
        _ => false,
    }
}

/// Every `<source>.meta.toml` sidecar found directly inside *dir* (not
/// recursive), paired with its source file — `sopack extract dir/
/// --meta-from-sidecars`'s discovery step. A sidecar whose source file no
/// longer exists is skipped (not an error): a stale sidecar left behind by
/// a rename is a cleanup nit, not a reason to abort a whole-folder batch.
pub fn discover_sidecars(dir: &Path) -> Result<Vec<(PathBuf, MetaFile)>, ExtractError> {
    let entries = std::fs::read_dir(dir)
        .map_err(|e| ExtractError::input_invalid(format!("cannot read {}: {e}", dir.display())))?;
    let mut out = Vec::new();
    let mut sidecar_paths: Vec<PathBuf> = Vec::new();
    for entry in entries {
        let entry =
            entry.map_err(|e| ExtractError::input_invalid(format!("{}: {e}", dir.display())))?;
        let path = entry.path();
        if path
            .file_name()
            .and_then(|n| n.to_str())
            .map(|n| n.ends_with(".meta.toml"))
            == Some(true)
        {
            sidecar_paths.push(path);
        }
    }
    sidecar_paths.sort();
    for sidecar_path in sidecar_paths {
        let name = sidecar_path
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("");
        let Some(source_name) = name.strip_suffix(".meta.toml") else {
            continue;
        };
        let source_path = dir.join(source_name);
        if !source_path.exists() {
            continue;
        }
        let meta = load(&sidecar_path)?;
        out.push((source_path, meta));
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::propose::propose_quiet;

    fn opts(
        book_code: Option<&str>,
        lang: Option<&str>,
        title: Option<&str>,
        corpus: Option<&str>,
    ) -> ExtractOptions {
        ExtractOptions {
            book_code: book_code.map(str::to_string),
            lang: lang.map(str::to_string),
            title: title.map(str::to_string),
            corpus: corpus.map(str::to_string),
            ..Default::default()
        }
    }

    #[test]
    fn load_parses_a_well_formed_sidecar() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("book.epub.meta.toml");
        std::fs::write(
            &path,
            "book_code = \"ATNW\"\nlang = \"en\"\ntitle = \"The Atonement\"\nyear = 1884\n\n[evidence]\ntitle = \"title page p.1\"\n",
        )
        .unwrap();
        let meta = load(&path).unwrap();
        assert_eq!(meta.book_code.as_deref(), Some("ATNW"));
        assert_eq!(meta.year, Some(1884));
        assert_eq!(
            meta.evidence.get("title").map(String::as_str),
            Some("title page p.1")
        );
    }

    #[test]
    fn load_rejects_malformed_toml() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("bad.meta.toml");
        std::fs::write(&path, "this is not = = toml").unwrap();
        assert!(load(&path).is_err());
    }

    #[test]
    fn from_meta_maps_every_field() {
        let meta = MetaFile {
            book_code: Some("ATNW".into()),
            lang: Some("en".into()),
            title: Some("The Atonement".into()),
            author: Some("J. H. Waggoner".into()),
            year: Some(1884),
            corpus: Some("pioneers".into()),
            slug: Some("waggoner-jh-the-atonement".into()),
            book_pair: Some("ATNW".into()),
            acquired_from: Some("archive.org/details/x".into()),
            rights: Some("public-domain".into()),
            evidence: HashMap::new(),
        };
        let opts = ExtractOptions::from_meta(&meta);
        assert_eq!(opts.book_code.as_deref(), Some("ATNW"));
        assert_eq!(opts.year, Some(1884));
        assert_eq!(opts.rights.as_deref(), Some("public-domain"));
    }

    #[test]
    fn merge_explicit_wins_when_sidecar_absent() {
        let explicit = opts(Some("ATNW"), None, None, None);
        let sidecar = opts(None, Some("en"), None, None);
        let merged = merge(&explicit, &sidecar).unwrap();
        assert_eq!(merged.book_code.as_deref(), Some("ATNW"));
        assert_eq!(merged.lang.as_deref(), Some("en"));
    }

    #[test]
    fn merge_agreeing_values_are_fine() {
        let explicit = opts(Some("ATNW"), None, None, None);
        let sidecar = opts(Some("ATNW"), None, None, None);
        let merged = merge(&explicit, &sidecar).unwrap();
        assert_eq!(merged.book_code.as_deref(), Some("ATNW"));
    }

    #[test]
    fn merge_conflicting_values_error() {
        let explicit = opts(Some("ATNW"), None, None, None);
        let sidecar = opts(Some("OTHER"), None, None, None);
        let err = merge(&explicit, &sidecar).unwrap_err();
        assert_eq!(err.field.as_deref(), Some("book_code"));
        assert_eq!(err.code, ErrorCode::Usage);
    }

    #[test]
    fn required_fields_per_kind() {
        assert_eq!(
            required_fields(Kind::Markdown),
            &["book_code", "lang", "title"]
        );
        assert_eq!(required_fields(Kind::Text), &["book_code", "lang", "title"]);
        assert_eq!(required_fields(Kind::Epub), &["book_code"]);
        assert_eq!(required_fields(Kind::SopJson), &[] as &[&str]);
    }

    #[test]
    fn check_complete_flags_missing_base_fields() {
        let missing = check_complete(Kind::Markdown, &opts(None, None, None, None));
        let fields: Vec<&str> = missing.iter().filter_map(|e| e.field.as_deref()).collect();
        assert!(fields.contains(&"book_code"));
        assert!(fields.contains(&"lang"));
        assert!(fields.contains(&"title"));
        for e in &missing {
            assert_eq!(e.code, ErrorCode::NeedsMetadata);
        }
    }

    #[test]
    fn check_complete_adds_author_year_when_corpus_given() {
        let missing = check_complete(
            Kind::Epub,
            &opts(Some("ATNW"), None, None, Some("pioneers")),
        );
        let fields: Vec<&str> = missing.iter().filter_map(|e| e.field.as_deref()).collect();
        assert!(fields.contains(&"author"));
        assert!(fields.contains(&"year"));
        assert!(!fields.contains(&"book_code")); // already given
    }

    #[test]
    fn check_complete_egw_epub_with_book_code_is_complete() {
        let missing = check_complete(Kind::Epub, &opts(Some("GC"), None, None, None));
        assert!(missing.is_empty());
    }

    #[test]
    fn check_complete_sop_json_never_requires_anything_from_opts() {
        assert!(check_complete(Kind::SopJson, &ExtractOptions::default()).is_empty());
    }

    #[test]
    fn discover_sidecars_pairs_existing_sources_only() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("a.epub"), b"stub").unwrap();
        std::fs::write(dir.path().join("a.epub.meta.toml"), "title = \"A\"\n").unwrap();
        // Sidecar with no matching source — must be skipped, not error.
        std::fs::write(dir.path().join("gone.epub.meta.toml"), "title = \"Gone\"\n").unwrap();

        let pairs = discover_sidecars(dir.path()).unwrap();
        assert_eq!(pairs.len(), 1);
        assert_eq!(pairs[0].0, dir.path().join("a.epub"));
        assert_eq!(pairs[0].1.title.as_deref(), Some("A"));
    }

    #[test]
    fn write_template_then_load_round_trips_resolved_fields() {
        let dir = tempfile::tempdir().unwrap();
        let src = dir.path().join("small.md");
        std::fs::write(
            &src,
            "# Steps to Christ\n\nBY ELLEN G. WHITE\n\nBody text goes here, enough words.\n",
        )
        .unwrap();

        let proposal = propose_quiet(&src, Some(Kind::Markdown), None).unwrap();
        let sidecar_path = dir.path().join("small.md.meta.toml");
        write_template(&proposal, &sidecar_path).unwrap();
        assert!(sidecar_path.is_file());

        let meta = load(&sidecar_path).unwrap();
        // Markdown has no title_page-equivalent authoritative source, so
        // everything propose found should still be commented (unresolved).
        assert!(meta.title.is_none());
        let text = std::fs::read_to_string(&sidecar_path).unwrap();
        assert!(text.contains("# title:"));
    }
}
