//! The offline book-code registry `propose` checks collision candidates
//! against — `sopack.book_codes/1`, generated by the importer-side
//! `qdrant/app/book_codes.py` from `app/data/sop_books.json` (the same
//! authority `sop_list_books` serves). Design: `SOPACK-1.0-PLAN.md` §3.2
//! "Book-code collisions are checked offline against a committed registry".
//!
//! This module only *reads* the registry — nothing here talks to Qdrant or
//! the network (P2). The registry file itself is a committed artifact
//! (`contracts/<contract>/book_codes.json`) refreshed by the importer's
//! admin command after every corpus import, same moment as
//! `export_book_titles.py`.

use std::collections::HashMap;
use std::path::Path;

use serde::Deserialize;
use unicode_normalization::UnicodeNormalization;

use crate::error::ExtractError;

/// One `codes[<CODE>]` row.
#[derive(Debug, Clone, Deserialize)]
pub struct RegistryEntry {
    pub title: Option<String>,
    #[serde(default)]
    pub lang: Vec<String>,
    pub corpus: Option<String>,
    pub slug: Option<String>,
    /// Author form as stored (e.g. "J. H. Waggoner"); absent for most EGW rows.
    #[serde(default)]
    pub author: Option<String>,
    /// The work's year as stored; lets a title match be confirmed by date.
    #[serde(default)]
    pub year: Option<i64>,
}

#[derive(Debug, Clone, Deserialize)]
struct RegistryFile {
    schema: String,
    generated_from: String,
    generated_at: String,
    codes: HashMap<String, RegistryEntry>,
}

/// The loaded `book_codes.json`. Cheap to hold: it is a few hundred short
/// rows, not the corpus itself.
#[derive(Debug, Clone)]
pub struct Registry {
    pub schema: String,
    pub generated_from: String,
    pub generated_at: String,
    codes: HashMap<String, RegistryEntry>,
}

const EXPECTED_SCHEMA: &str = "sopack.book_codes/1";

impl Registry {
    /// Load and structurally validate *path*. Rejects an unrecognised
    /// `schema` rather than silently reading a future/incompatible shape —
    /// same "refuse rather than guess" posture as the rest of this crate.
    pub fn load(path: &Path) -> Result<Registry, ExtractError> {
        let text = std::fs::read_to_string(path).map_err(|e| {
            ExtractError::input_invalid(format!(
                "cannot read book-code registry {}: {e}",
                path.display()
            ))
        })?;
        let parsed: RegistryFile = serde_json::from_str(&text).map_err(|e| {
            ExtractError::input_invalid(format!(
                "{}: not a valid book_codes.json: {e}",
                path.display()
            ))
        })?;
        if parsed.schema != EXPECTED_SCHEMA {
            return Err(ExtractError::input_invalid(format!(
                "{}: unsupported registry schema {:?} (expected {:?})",
                path.display(),
                parsed.schema,
                EXPECTED_SCHEMA
            )));
        }
        Ok(Registry {
            schema: parsed.schema,
            generated_from: parsed.generated_from,
            generated_at: parsed.generated_at,
            codes: parsed.codes,
        })
    }

    /// An empty registry (every `book_code` candidate reports `collision:
    /// false`). What `propose` falls back to when no `--registry` path is
    /// given — offline collision checking is best-effort, not mandatory.
    pub fn empty() -> Registry {
        Registry {
            schema: EXPECTED_SCHEMA.to_string(),
            generated_from: String::new(),
            generated_at: String::new(),
            codes: HashMap::new(),
        }
    }

    /// Whether *code* is already a row in the registry (a literal
    /// `book_code` string match — see `book_codes.py`'s docstring on why
    /// two languages using the same string collapse into one row).
    pub fn contains(&self, code: &str) -> bool {
        self.codes.contains_key(code)
    }

    pub fn get(&self, code: &str) -> Option<&RegistryEntry> {
        self.codes.get(code)
    }

    pub fn len(&self) -> usize {
        self.codes.len()
    }

    pub fn is_empty(&self) -> bool {
        self.codes.is_empty()
    }

    /// Every registry row whose title matches *title* once both are
    /// normalised — the real re-import detector (`SOPACK-1.0-PLAN.md` §3.2).
    ///
    /// A real incident this exists to catch: the conversion manifest
    /// proposed a fresh code for "An Explanation of the Typical and
    /// Anti-typical Sanctuary by the Scriptures, with a Chart", but the
    /// live store already held that exact work as `BP3` — `propose` only
    /// checked its own *code* candidates for collisions, so it never looked
    /// at the registry's *titles* and reported "no collision" for a work
    /// that would have been silently duplicated under a new code.
    ///
    /// Two match strengths, weakest first among ties in the result order
    /// (full matches are pushed first):
    /// - [`TitleMatchKind::Full`] — the two titles are identical once
    ///   [`normalize_title`] has folded case, stripped diacritics/
    ///   punctuation and collapsed whitespace.
    /// - [`TitleMatchKind::Short`] — only the "short title" (the text
    ///   before the first `;`, `:` or `, or` — the pre-1900 title-page
    ///   convention for a discursive subtitle, e.g. "Steps to Christ; or,
    ///   The Sinner's Guide") matches; the full titles differ, so this is
    ///   weaker evidence and the caller should ask for confirmation.
    ///
    /// *lang* restricts the search to registry rows that carry that
    /// language among their `lang[]` — a row with no recorded language is
    /// never excluded, since that is missing data, not a language
    /// mismatch. Rows with no `title` at all are skipped.
    pub fn find_by_title(&self, title: &str, lang: Option<&str>) -> Vec<TitleMatch> {
        let norm_full = normalize_title(title);
        if norm_full.is_empty() {
            return Vec::new();
        }
        let norm_short = normalize_title(short_title(title));

        let mut full_matches = Vec::new();
        let mut short_matches = Vec::new();
        for (code, entry) in &self.codes {
            let Some(entry_title) = &entry.title else {
                continue;
            };
            if let Some(lang) = lang {
                if !entry.lang.is_empty() && !entry.lang.iter().any(|l| l == lang) {
                    continue;
                }
            }
            if normalize_title(entry_title) == norm_full {
                full_matches.push(TitleMatch {
                    code: code.clone(),
                    entry_title: entry_title.clone(),
                    kind: TitleMatchKind::Full,
                });
                continue;
            }
            if !norm_short.is_empty() && normalize_title(short_title(entry_title)) == norm_short {
                short_matches.push(TitleMatch {
                    code: code.clone(),
                    entry_title: entry_title.clone(),
                    kind: TitleMatchKind::Short,
                });
            }
        }
        full_matches.sort_by(|a, b| a.code.cmp(&b.code));
        short_matches.sort_by(|a, b| a.code.cmp(&b.code));
        full_matches.extend(short_matches);
        full_matches
    }
}

/// How strongly a [`Registry::find_by_title`] hit matched.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TitleMatchKind {
    /// The full, normalised titles are identical.
    Full,
    /// Only the normalised "short title" (see [`short_title`]) matched.
    Short,
}

/// One [`Registry::find_by_title`] hit.
#[derive(Debug, Clone)]
pub struct TitleMatch {
    pub code: String,
    /// The registry row's own (un-normalised) title, for evidence text.
    pub entry_title: String,
    pub kind: TitleMatchKind,
}

/// Case-folds, strips diacritics and punctuation, and collapses whitespace,
/// so two independent transcriptions of the same title (curly vs. straight
/// quotes, an accented vs. unaccented loanword, extra spacing) compare
/// equal. NFD-decomposes first so an accented letter becomes base letter +
/// combining mark, then drops every combining mark.
pub fn normalize_title(title: &str) -> String {
    let mut out = String::with_capacity(title.len());
    let mut pending_space = false;
    for ch in title.nfd() {
        if unicode_normalization::char::is_combining_mark(ch) {
            continue;
        }
        if ch.is_alphanumeric() {
            if pending_space && !out.is_empty() {
                out.push(' ');
            }
            pending_space = false;
            for lc in ch.to_lowercase() {
                out.push(lc);
            }
        } else {
            pending_space = true;
        }
    }
    out
}

/// The text before the first `;`, `:` or `, or` in *title* — the pre-1900
/// title-page convention for a discursive subtitle ("Steps to Christ; or,
/// The Sinner's Guide to Peace with God"). Falls back to the whole title
/// when none of the three delimiters appear. Searches on an ASCII-lowercased
/// copy (not a full Unicode case fold) purely so the byte offsets it finds
/// stay valid on the original `title` slice — ASCII-only folding can never
/// change a string's length or split a UTF-8 code point.
pub fn short_title(title: &str) -> &str {
    let lower = title.to_ascii_lowercase();
    let idx = [lower.find(';'), lower.find(':'), lower.find(", or")]
        .into_iter()
        .flatten()
        .min();
    match idx {
        Some(i) => title[..i].trim_end(),
        None => title,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    fn write_registry(json: &str) -> tempfile::NamedTempFile {
        let mut f = tempfile::NamedTempFile::new().unwrap();
        f.write_all(json.as_bytes()).unwrap();
        f
    }

    #[test]
    fn loads_a_well_formed_registry() {
        let f = write_registry(
            r#"{"schema":"sopack.book_codes/1","generated_from":"app/data/sop_books.json",
                "generated_at":"2026-09-24T00:00:00Z",
                "codes":{"SC":{"title":"Steps to Christ","lang":["en"],"corpus":null,"slug":null}}}"#,
        );
        let reg = Registry::load(f.path()).unwrap();
        assert_eq!(reg.len(), 1);
        assert!(reg.contains("SC"));
        assert!(!reg.contains("ATNW"));
        assert_eq!(
            reg.get("SC").unwrap().title.as_deref(),
            Some("Steps to Christ")
        );
    }

    #[test]
    fn rejects_wrong_schema() {
        let f = write_registry(
            r#"{"schema":"sopack.book_codes/2","generated_from":"x",
                "generated_at":"x","codes":{}}"#,
        );
        let err = Registry::load(f.path()).unwrap_err();
        assert!(err.message.contains("unsupported registry schema"));
    }

    #[test]
    fn rejects_malformed_json() {
        let f = write_registry("not json");
        assert!(Registry::load(f.path()).is_err());
    }

    #[test]
    fn empty_registry_never_collides() {
        let reg = Registry::empty();
        assert!(!reg.contains("ANYTHING"));
        assert!(reg.is_empty());
    }

    // ---------------------------------------------------------- normalize_title

    #[test]
    fn normalize_title_folds_case_punctuation_and_whitespace() {
        assert_eq!(
            normalize_title(
                "An Explanation of the Typical and Anti-typical Sanctuary by the Scriptures, with a Chart"
            ),
            "an explanation of the typical and anti typical sanctuary by the scriptures with a chart"
        );
        // Extra/irregular whitespace and curly punctuation collapse the
        // same way — two independent transcriptions of the same work.
        assert_eq!(
            normalize_title("  The   Cross\u{2019}s  Shadow!! "),
            "the cross s shadow"
        );
    }

    #[test]
    fn normalize_title_strips_diacritics() {
        assert_eq!(normalize_title("Café \u{100}pple"), "cafe apple");
        assert_eq!(normalize_title("Über Grüße"), "uber gruße");
    }

    #[test]
    fn normalize_title_empty_for_pure_punctuation() {
        assert_eq!(normalize_title("---"), "");
    }

    // ---------------------------------------------------------------- short_title

    #[test]
    fn short_title_splits_on_semicolon_colon_and_comma_or() {
        assert_eq!(
            short_title("Steps to Christ; or, The Sinner's Guide"),
            "Steps to Christ"
        );
        assert_eq!(
            short_title("The Great Controversy: Between..."),
            "The Great Controversy"
        );
        assert_eq!(
            short_title("The Cross and Its Shadow, or The Sanctuary Explained"),
            "The Cross and Its Shadow"
        );
    }

    #[test]
    fn short_title_falls_back_to_whole_title_when_no_delimiter() {
        assert_eq!(short_title("Steps to Christ"), "Steps to Christ");
        assert_eq!(
            short_title(
                "An Explanation of the Typical and Anti-typical Sanctuary by the Scriptures, with a Chart"
            ),
            "An Explanation of the Typical and Anti-typical Sanctuary by the Scriptures, with a Chart"
        );
    }

    #[test]
    fn short_title_picks_the_earliest_delimiter() {
        // ':' at index 5 comes before ', or' later in the string.
        assert_eq!(short_title("Title: Sub, or Alt"), "Title");
    }

    // ------------------------------------------------------------ find_by_title

    fn registry_with(codes_json: &str) -> Registry {
        let json = format!(
            r#"{{"schema":"sopack.book_codes/1","generated_from":"app/data/sop_books.json",
                "generated_at":"2026-09-24T00:00:00Z","codes":{codes_json}}}"#
        );
        let f = write_registry(&json);
        Registry::load(f.path()).unwrap()
    }

    #[test]
    fn find_by_title_matches_the_real_bates_tats_bp3_incident() {
        // The real incident this feature exists to catch: TATS was
        // proposed as a fresh code for a work the live store already holds
        // as BP3, under a title that differs only in punctuation-as-comma
        // vs none and possibly whitespace from what a fresh scan produces.
        let reg = registry_with(
            r#"{"BP3":{"title":"An Explanation of the Typical and Anti-typical Sanctuary by the Scriptures, with a Chart","lang":["en"],"corpus":"pioneers","slug":null}}"#,
        );
        let hits = reg.find_by_title(
            "An Explanation of the Typical and Anti-typical Sanctuary by the Scriptures, with a Chart",
            Some("en"),
        );
        assert_eq!(hits.len(), 1);
        assert_eq!(hits[0].code, "BP3");
        assert_eq!(hits[0].kind, TitleMatchKind::Full);
    }

    #[test]
    fn find_by_title_full_match_is_insensitive_to_case_and_punctuation_drift() {
        let reg = registry_with(
            r#"{"SC":{"title":"Steps to Christ","lang":["en"],"corpus":null,"slug":null}}"#,
        );
        let hits = reg.find_by_title("STEPS TO CHRIST.", Some("en"));
        assert_eq!(hits.len(), 1);
        assert_eq!(hits[0].code, "SC");
        assert_eq!(hits[0].kind, TitleMatchKind::Full);
    }

    #[test]
    fn find_by_title_short_title_match_is_weaker_than_full() {
        let reg = registry_with(
            r#"{"CIS":{"title":"The Cross and Its Shadow; or, The Sanctuary Explained","lang":["en"],"corpus":"pioneers","slug":null}}"#,
        );
        // A candidate title that only agrees on the part before the
        // subtitle delimiter — still a candidate, but Short not Full.
        let hits = reg.find_by_title("The Cross and Its Shadow", Some("en"));
        assert_eq!(hits.len(), 1);
        assert_eq!(hits[0].code, "CIS");
        assert_eq!(hits[0].kind, TitleMatchKind::Short);
    }

    #[test]
    fn find_by_title_respects_lang_filter_but_not_missing_lang_data() {
        let reg = registry_with(
            r#"{"DE1":{"title":"Steps to Christ","lang":["de"],"corpus":null,"slug":null},
                "NOLANG":{"title":"Steps to Christ","lang":[],"corpus":null,"slug":null}}"#,
        );
        // Requesting "en" must exclude the German-only row...
        let hits = reg.find_by_title("Steps to Christ", Some("en"));
        let codes: Vec<&str> = hits.iter().map(|m| m.code.as_str()).collect();
        assert!(!codes.contains(&"DE1"), "{codes:?}");
        // ...but a row with no recorded lang at all is never excluded —
        // missing data is not a language mismatch.
        assert!(codes.contains(&"NOLANG"), "{codes:?}");
    }

    #[test]
    fn find_by_title_no_match_for_an_unrelated_title() {
        let reg = registry_with(
            r#"{"SC":{"title":"Steps to Christ","lang":["en"],"corpus":null,"slug":null}}"#,
        );
        let hits = reg.find_by_title("The Great Controversy", Some("en"));
        assert!(hits.is_empty());
    }

    #[test]
    fn find_by_title_empty_query_matches_nothing() {
        let reg = registry_with(
            r#"{"SC":{"title":"Steps to Christ","lang":["en"],"corpus":null,"slug":null}}"#,
        );
        assert!(reg.find_by_title("", Some("en")).is_empty());
        assert!(reg.find_by_title("---", Some("en")).is_empty());
    }
}
