//! Copies the released e5-large-v1 calibration fixture into `OUT_DIR` so
//! `src/contract.rs` can `include_str!` it unconditionally.
//!
//! `calibration.json` is generated by a separate, server-side admin command
//! (SOPACK-2-FORMAT.md §3) and, as of this crate's initial build, does not
//! exist yet — `include_str!("../../../contracts/e5-large-v1/calibration.json")`
//! directly in `src/` would fail to compile until that file lands. Copying it
//! through `OUT_DIR` here means: if the file is present, its real bytes are
//! embedded; if it is absent, an empty placeholder is embedded instead, and
//! `Contract::embedded` reports a clear "not yet generated" error at run time
//! rather than a build failure. `cargo:rerun-if-changed` means a real run of
//! this build script picks up the fixture the moment the other agent writes
//! it, with no code change here.

use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir =
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR is set by cargo");

    let src = Path::new(&manifest_dir).join("../../contracts/e5-large-v1/calibration.json");
    let dst = Path::new(&out_dir).join("calibration_e5_large_v1.json");

    println!("cargo:rerun-if-changed={}", src.display());

    match fs::read(&src) {
        Ok(bytes) => {
            fs::write(&dst, bytes).expect("failed to copy calibration fixture into OUT_DIR")
        }
        Err(_) => fs::write(&dst, b"").expect("failed to write empty calibration placeholder"),
    }
}
