//! M2 id conformance: reproduces every golden `{rule, fields, uid, id}` case
//! in `qdrant/sopack-rs/conformance/ids/golden.json` — a frozen golden,
//! generated by the retired Python reference implementation against the same
//! `contracts/e5-large-v1/contract.toml` this crate embeds (the server's
//! `app/pack/contract.py` still computes ids the same way). Proves the Rust
//! `IdRule` template engine (uid substitution + `uuid5(NAMESPACE_DNS, uid)`)
//! agrees with that reference, not just with itself. See
//! `conformance/README.md`.

use serde::Deserialize;
use serde_json::{Map, Value};
use sopack_contract::Contract;

#[derive(Debug, Deserialize)]
struct GoldenCase {
    rule: String,
    fields: Map<String, Value>,
    uid: String,
    id: String,
}

#[test]
fn ids_conformance_matches_python_contract_py() {
    let golden: Vec<GoldenCase> = serde_json::from_str(include_str!(
        "../../../conformance/ids/golden.json"
    ))
    .expect("conformance/ids/golden.json must parse — it is a frozen golden from the retired Python implementation");
    assert!(!golden.is_empty(), "golden.json has no cases");

    let contract =
        Contract::embedded("e5-large-v1").expect("the embedded e5-large-v1 contract must load");

    for case in &golden {
        let rule = contract
            .get_id_rule(&case.rule)
            .unwrap_or_else(|e| panic!("golden case names unknown id rule {:?}: {e}", case.rule));

        let uid = rule.build_uid(&case.fields).unwrap_or_else(|e| {
            panic!(
                "build_uid failed for rule {:?} fields {:?}: {e}",
                case.rule, case.fields
            )
        });
        assert_eq!(
            uid, case.uid,
            "uid mismatch for rule {:?} fields {:?} (Python: {:?}, Rust: {:?})",
            case.rule, case.fields, case.uid, uid
        );

        let id = rule.point_id(&case.fields).unwrap_or_else(|e| {
            panic!(
                "point_id failed for rule {:?} fields {:?}: {e}",
                case.rule, case.fields
            )
        });
        assert_eq!(
            id, case.id,
            "point id mismatch for rule {:?} fields {:?} (Python: {:?}, Rust: {:?})",
            case.rule, case.fields, case.id, id
        );
    }
}
